# global mofa settings

# Admin User Account that should be used for all mofa tasks.
# The user has to be able to login passwordless
# and has tohave passwordless sudo permissions.
ssh_user: jenkins
ssh_keyfile: ~/.ssh/id_rsa

# where to build tmporary cookbook packages and so on
tmp_dir: /var/tmp

service_hostlist_url: file:///var/lib/jenkins/hostlist.json
service_hostlist_default_filter: "*.pingworks.net"

# The cookbook architectural pattern should becodified by following
# a coonaming schema:
# * Cookbooks beginning with "env_*" are Envrionment Cookbooks
# * Cookbooks haven a prefix like "<organisation_name>_*" are
#   so-called Wrapper Cookbooks
# * Cookbooks having a "base_" Prefix are Base Cookbooks

cookbook_type_indicator:
  env: "^ws-env_.*"
  wrapper: "^(foo_|bar_).*"
  base: ".*_base$"

# Where to find released binary packages of Cookbooks.
bin_repo: http://repo/cookbooks/
binrepo_host: repo
binrepo_ssh_port: 22
binrepo_ssh_user: jenkins
binrepo_ssh_keyfile: ~/.ssh/id_rsa
binrepo_import_dir: /data/cookbooks
